spring:
  application:
    name: server
  sql:
    init:
      encoding: UTF-8
      mode: never
  datasource:
    url: ${DB_URL}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
  session:
    redis:
      namespace: dku-exchange:session
    timeout: ${SESSION_TIMEOUT}
  ai:
    openai:
      base-url: ${LLM_OPENAI_BASE_URL}
      api-key: ${LLM_API_KEY}
      chat:
        completions-path: /chat/completions

llm:
  model:
    standard:
      name: ${LLM_STANDARD_MODEL}
      temperature: ${LLM_STANDARD_TEMPERATURE}
    lite:
      name: ${LLM_LITE_MODEL}
      temperature: ${LLM_LITE_TEMPERATURE}

server:
  forward-headers-strategy: framework

debug: false
